syntax = "proto3";

package project.khaihust.foqs.core.proto;

option java_multiple_files = true;
option java_package = "project.khaihust.foqs.core.proto";
option java_outer_classname = "DequeueProto";

service DequeueService {
  rpc Dequeue (DequeueRequestDto) returns (DequeueResponseDto);
  rpc BatchAck(BatchAckRequestDto) returns (BatchAckResponseDto);
  rpc BatchNack(BatchNackRequestDto) returns (BatchNackResponseDto);
}

message DequeueRequestDto {
  string topic = 1;
  int32 count = 2;
  int32 timeout = 3;
}

message DequeueResponseDto {
  repeated DequeuedMessageDto messages = 1;
}

message DequeuedMessageDto {
  string message_id = 1;
  string topic = 2;
  int32 priority = 3;
  bytes payload = 4;
  int64 lease_until_epoch_ms = 5;
  int32 retry_count = 6;
  int64 created_at_epoch_ms = 7;
}

message BatchAckRequestDto {
  repeated string message_ids = 1;
}

message BatchAckResponseDto {
  repeated string acked_message_ids = 1;
  repeated string failed_message_ids = 2;
}

message BatchNackRequestDto {
  repeated string message_ids = 1;
  int64 retry_delay_ms = 2;
  int32 max_retry_count = 3;
}

message BatchNackResponseDto {
  int32 successCount = 1;
}